# Generated by Django 5.0 on 2023-12-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='favicon',
            field=models.URLField(blank=True, default='null', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_name',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(blank=True, default='null', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
